# Generated by Django 2.1.5 on 2019-02-12 07:14

from django.db import migrations, models
import django.db.models.deletion
import staircase.models.Measurements.Raw_data_file
import staircase.models.model_functions.add_configuration_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamberName', models.CharField(max_length=30)),
                ('chamberPosition', models.CharField(blank=True, max_length=30, null=True)),
                ('chamberDescription', models.CharField(blank=True, max_length=10000, null=True)),
                ('descriptionFile', models.FileField(blank=True, null=True, upload_to=staircase.models.model_functions.add_configuration_file.add_configuration_file)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChamberPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=30)),
                ('partNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Chamber')),
            ],
        ),
        migrations.CreateModel(
            name='Foup',
            fields=[
                ('foupname', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Foup Name')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foup_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('foup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staircase.Foup')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrologyname', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('recipeNote', models.CharField(max_length=200)),
                ('recipeDetail', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Chamber')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_data_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='thickness', max_length=200)),
                ('rawDataFile', models.FileField(blank=True, null=True, upload_to=staircase.models.Measurements.Raw_data_file.add_raw_data_file)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=200)),
                ('measureType', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metrology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Metrology')),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Chamber')),
                ('followingProcess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Split')),
                ('foup_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Foup_slot')),
                ('processRecipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.ProcessRecipe')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rawthk', models.CharField(blank=True, max_length=10000, null=True)),
                ('rawX', models.CharField(blank=True, max_length=10000, null=True)),
                ('rawY', models.CharField(blank=True, max_length=10000, null=True)),
                ('rawRI', models.CharField(blank=True, max_length=10000, null=True)),
                ('rawGOF', models.CharField(blank=True, max_length=10000, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('rawDataFile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Raw_data_file')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Recipe')),
                ('split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Split')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Wafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isUsed', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=10)),
                ('wafertype', models.CharField(choices=[('PT', 'Particle Grade Wafer'), ('LR', 'Low Res Particle Grade Wafer'), ('MC', 'Mechanical Grade Wafer'), ('ER', 'External Reclaimed Wafer'), ('IR', 'Internal Reclaimed Wafer')], default='Internal Reclaimed Wafer', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='split',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.User'),
        ),
        migrations.AddField(
            model_name='split',
            name='wafer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Wafer'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='supportingProject',
            field=models.ManyToManyField(related_name='_project_supportingProject_+', to='staircase.Project'),
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupmanager', to='staircase.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Group'),
        ),
        migrations.AddField(
            model_name='foup_slot',
            name='wafer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Wafer'),
        ),
        migrations.AddField(
            model_name='foup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.User'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='chamberOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.User'),
        ),
    ]
