# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staircase', '0002_auto_20170527_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='chamberDescription',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='chamberPosition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
