# Generated by Django 2.1.5 on 2019-02-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staircase', '0003_auto_20170527_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrecipe',
            name='chamber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Chamber'),
        ),
        migrations.AddField(
            model_name='processrecipe',
            name='recipeDetail',
            field=models.CharField(default='no recipe detail', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staircase.Group'),
        ),
    ]
